/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import Configuration.Configuration;
import java.awt.List;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shihab Rashel
 */
public class Prescription extends javax.swing.JFrame {

    /**
     * Creates new form Prescription
     */
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    private int doctorId;
    private int patientId;
    ArrayList<String[]> medicineList = new ArrayList<String[]>();
    public Prescription() {
        con=Configuration.GetConnection();
        initComponents();
    }

    public Prescription(int dId, int pId) {
        this.medicineList = new ArrayList<String[]>();
        this.doctorId=dId;
        this.patientId=pId;
        con=Configuration.GetConnection();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtMedicine = new javax.swing.JTextField();
        txtMedicineQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtReport = new javax.swing.JTextField();
        btnAddMedicineAndReport = new javax.swing.JButton();
        btnRemoveMedicineAndReport = new javax.swing.JButton();
        btnSavePrescription = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPrescriptionDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrescription = new javax.swing.JTable();
        btnPrescriptionPrint = new javax.swing.JButton();

        setTitle("Prescribe");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Medicine");

        jLabel2.setText("Report");

        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicineMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMedicine);

        jLabel3.setText("Medicine");

        jLabel4.setText("Report");

        btnAddMedicineAndReport.setText("+");
        btnAddMedicineAndReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineAndReportActionPerformed(evt);
            }
        });

        btnRemoveMedicineAndReport.setText("-");
        btnRemoveMedicineAndReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMedicineAndReportActionPerformed(evt);
            }
        });

        btnSavePrescription.setText("Save");
        btnSavePrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePrescriptionActionPerformed(evt);
            }
        });

        jLabel5.setText("Date");

        txtPrescriptionDate.setEditable(false);

        tblPrescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrescription);

        btnPrescriptionPrint.setText("Print");
        btnPrescriptionPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrescriptionPrint)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSavePrescription)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel1)
                                    .addGap(113, 113, 113)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnRemoveMedicineAndReport)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnAddMedicineAndReport))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtReport))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtMedicineQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtPrescriptionDate))))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrescriptionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedicineQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddMedicineAndReport)
                            .addComponent(btnRemoveMedicineAndReport))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnPrescriptionPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSavePrescription)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMedicineAndReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineAndReportActionPerformed
        String[] medicine=new String[3];
        medicine[0]=txtMedicine.getText();
        medicine[1]=txtMedicineQuantity.getText();
        medicine[2]=txtReport.getText();
        medicineList.add(medicine);
        LoadMedicineAndPrescription();
    }//GEN-LAST:event_btnAddMedicineAndReportActionPerformed

    private void tblMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicineMouseClicked
//        int selectedRowIndex=tblMedicine.getSelectedRow();
//        TableModel model=tblMedicine.getModel();
//        txtMedicine.setText(model.getValueAt(selectedRowIndex,0).toString());
//        txtMedicineQuantity.setText(model.getValueAt(selectedRowIndex,1).toString());
//        txtReport.setText(model.getValueAt(selectedRowIndex,2).toString());
    }//GEN-LAST:event_tblMedicineMouseClicked

    private void btnRemoveMedicineAndReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMedicineAndReportActionPerformed
        medicineList.remove(medicineList.size()-1);
        LoadMedicineAndPrescription();
    }//GEN-LAST:event_btnRemoveMedicineAndReportActionPerformed

    private void btnSavePrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePrescriptionActionPerformed
        if(medicineList.size()<=0)
        {
            JOptionPane.showMessageDialog(null, "Add medicine and report first");
            return;
        }
        
        for (String[] medicine : medicineList) {
            try{
                ps=con.prepareStatement("Insert into prescription (Doctorid,PatientId,Date,MedicineId,MedicineQuantity,ReportId) Values('"+doctorId+"','"+patientId+"','"+txtPrescriptionDate.getText()+"','"+medicine[0]+"','"+medicine[1]+"','"+medicine[2]+"')");
                int result=ps.executeUpdate();
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.ERROR);
                 return;
            }
        }
        JOptionPane.showMessageDialog(null, "Prescription Added");
        LoadPrescription();
    }//GEN-LAST:event_btnSavePrescriptionActionPerformed
    private void LoadPrescription(){
        try {
            ps=con.prepareStatement("SELECT p.Id as PatienID,p.Name as PatientName,pr.MedicineId as Medicine,pr.MedicineQuantity,pr.ReportId as Report,pr.Date from patient p JOIN prescription pr on pr.PatientId=p.Id='"+patientId+"' AND pr.Date='"+txtPrescriptionDate.getText()+"' and pr.Doctorid='"+doctorId+"'");
            rs=ps.executeQuery();
            tblPrescription.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Prescription.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String timeStamp = new SimpleDateFormat("yyyyMMdd").format(Calendar.getInstance().getTime());
        System.out.println(timeStamp);
        txtPrescriptionDate.setText(timeStamp);
    }//GEN-LAST:event_formWindowOpened

    private void btnPrescriptionPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionPrintActionPerformed
        MessageFormat header=new MessageFormat("Prescripstion");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try {
            tblPrescription.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnPrescriptionPrintActionPerformed
    private void LoadMedicineAndPrescription(){
        tblMedicine.setModel(new DefaultTableModel(medicineList.toArray(new Object[][] {}), 
                        new String[] {"Medicine", "Quantity", "Report"}));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicineAndReport;
    private javax.swing.JButton btnPrescriptionPrint;
    private javax.swing.JButton btnRemoveMedicineAndReport;
    private javax.swing.JButton btnSavePrescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JTable tblPrescription;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtMedicineQuantity;
    private javax.swing.JTextField txtPrescriptionDate;
    private javax.swing.JTextField txtReport;
    // End of variables declaration//GEN-END:variables
}
